### ISSUE TITLE
Support for img2img

### ISSUE THREAD

**Issue by ghost** [wl-zhao/UniPC#6]
Hello, I have seen that the uniPC sampler is now supported by AUTO1111. I love the fast and good results I am getting, its quite a nice speed boost and it works together with ControlNet! Its incredible!

What would be needed for it to support img2img and inpainting? Is it easy or rather difficult to integrate? I'm not a python expert and I never took apart how a sampler works in terms of code

**Comment by wl-zhao** [comment]
Hi, 
thanks for your appreciation of our work. I think the img2img or inpainting is regardless of the sampler, (for example, our gradio demo has already supported img2img). However, since I am not very familiar with the stable-diffusion-webui codebase, I think it would be better to add a feature request in their [repo](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please also give me a link of the issue when you have created the feature request, and I will join the discussion as well.

**Comment by ghost** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8502

Thanks for your support!!

**Comment by EllangoK** [comment]
Hello, thanks first of all for making UniPC its probably the best current sampler.

I notice you mentioned that

> Hi, thanks for your appreciation of our work. I think the img2img or inpainting is regardless of the sampler, (for example, our gradio demo has already supported img2img). 

In the linked issue me and another user attempted the [demo on hugging face](https://huggingface.co/spaces/wl-zhao/unipc_sdm) but it did not work for img2img, only txt2img and kept on erroring it.

I did try with a 512 by 512 square image in case there were any issues with sizes or anything.

Is there maybe an issue with the huggingspaces demo? Have you previously checked if img2img worked on there? We would love to get it working with stable diffusion webui as well.

**Comment by wl-zhao** [comment]
Sorry, I just checked it and find the error was caused by the wrong version of the diffusers. The interface of img2img has been changed a little in the newest release of diffusers. I have fixed the bug and it should work as normal.
